version: '3.7'

volumes:
  mainfolder:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}

services:  
  pygfsv2:
    build: ./container/
    container_name: pygfsv2
    volumes:
      - mainfolder:/usr/src/app:z

